### ISSUE TITLE
Build with JDK 1.8 and 11 is broken

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree-ogcapi#15]
After merged PR #10 the build for JDK 1.8 is broken. 
Build error:
```
Error Message

org.glassfish.jersey.server.ServerExecutorProvidersConfigurator.registerExecutors(Lorg/glassfish/jersey/internal/inject/InjectionManager;Lorg/glassfish/jersey/model/internal/ComponentBag;Lorg/glassfish/jersey/spi/ExecutorServiceProvider;Lorg/glassfish/jersey/spi/ScheduledExecutorServiceProvider;)V

Stacktrace

java.lang.NoSuchMethodError: org.glassfish.jersey.server.ServerExecutorProvidersConfigurator.registerExecutors(Lorg/glassfish/jersey/internal/inject/InjectionManager;Lorg/glassfish/jersey/model/internal/ComponentBag;Lorg/glassfish/jersey/spi/ExecutorServiceProvider;Lorg/glassfish/jersey/spi/ScheduledExecutorServiceProvider;)V

Standard Output

[02:52:53]  WARN: [GMLSchemaInfoSet] Unhandled particle: MODEL_GROUP
[02:52:53]  WARN: [GMLSchemaInfoSet] Unhandled particle: MODEL_GROUP
[02:52:53]  WARN: [GMLSchemaInfoSet] Unhandled particle: MODEL_GROUP

Standard Error

Feb 17, 2022 2:52:53 AM org.glassfish.jersey.test.inmemory.InMemoryTestContainerFactory$InMemoryTestContainer <init>
INFO: Creating InMemoryTestContainer configured at the base URI http://localhost:9998/

```

ref: https://buildserver.deegree.org/view/deegree-ogcapi/job/deegree-ogcapi-BUILD/37/

**Comment by tfr42** [comment]
Build with JDK 11 is also affected.
